/* eslint-disable prettier/prettier */
// import React from 'react'

export const inputs = [
  {
    id: 1,
    name: 'businessname',
    type: 'text',
    placeholder: 'businessname',
    errorMessage: 'businessname should be 3-20 characters',
    label: 'businessname',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'businessname',
    // value: values.firstname,
  },
  {
    id: 2,
    name: 'select category',
    type: 'select',
    options: [
      { label: 'business', value: '1' },
      { label: 'businessowner', value: '2' },
    ],
    errorMessage: 'Last name should be 3-20 characters',
    label: 'select category',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'selectcategory',
  },
  {
    id: 3,
    name: 'companylogo',
    type: 'file',
    placeholder: 'choose file',
    errorMessage: 'User name should be 3-20 characters',
    label: 'Company logo',
    accept: 'image/png, image/jpeg',
    required: true,
    className: 'companylogo',
  },
  {
    id: 4,
    name: 'countryitem',
    type: 'text',
    placeholder: 'country',
    errorMessage: 'country should be 3-20 characters',
    label: 'country',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'countryitem',
    // value: values.firstname,
  },
  {
    id: 5,
    name: 'districtitem',
    type: 'text',
    placeholder: 'district',
    errorMessage: 'district should be 3-20 characters',
    label: 'district',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'districtitem',
  },
  {
    id: 6,
    name: 'cellitem',
    type: 'text',
    placeholder: 'cellitem',
    errorMessage: 'cell should be 3-20 characters',
    label: 'cell',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'cellitem',
  },
  {
    id: 7,
    name: 'villageitem',
    type: 'text',
    placeholder: 'villageitem',
    errorMessage: 'village should be 3-20 characters',
    label: 'village',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'villageitem',
    // value: values.firstname,
  },
  {
    id: 8,
    name: 'streetitem',
    type: 'text',
    placeholder: 'streetitem',
    errorMessage: 'street should be 3-20 characters',
    label: 'streetitem',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'streetitem',

  },
  {
    id: 9,
    name: 'phoneitem',
    type: 'text',
    placeholder: 'phoneitem',
    errorMessage: 'phoneitem should be 3-20 characters',
    label: 'phoneitem',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'phoneitem',
    
  },
  {
    id: 10,
    name: 'currencyitem',
    type: 'text',
    placeholder: 'currencyitem',
    errorMessage: 'currencyitem should be 3-20 characters',
    label: 'currencyitem',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'currencyitem',

  },
  {
    id: 11,
    name: 'tinitem',
    type: 'text',
    placeholder: 'tinitem',
    errorMessage: 'User name should be 3-20 characters',
    label: 'tinitem',
    pattern: `^.{3,20}$`,
    required: true,
    className: 'tinitem',

  },
  {
    id: 12,
    name: 'websiteitem',
    type: 'text',
    placeholder: 'websiteitem',
    className: 'websiteitem',
    errorMessage: 'websiteitem should be 3-20 characters',
    label: 'websiteitem',
    pattern: `^.{3,20}$`,
    required: true,

  },
  {
    id: 13,
    name: 'workspace',
    type: 'radio',
    options: [
      { label: 'owned', value: '1' },
      { label: 'rental', value: '2' },
    ],
    errorMessage: 'please choose here',
    label: 'workspace',
    required: true,
    className: 'workspace',

  },
  {
    id: 14,
    name: 'aboutbusiness',
    type: 'textarea',
    placeholder: 'please fill in about the business',
    errorMessage: 'please fill in..',
    label: 'about business',
    required: true,
    className: 'aboutbusiness',

  },
]
